debtors/urls.py
from django.conf.urls import url
from . import views

app_name = "debtors"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),



]

directory/urls.py
from django.conf.urls import url, include
from django.contrib import admin

admin.site.site_header = "Debtors Administration"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^debtors/', include('debtors.urls')),
]

debtors/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Paylater_Debtor(models.Model):
    AccountHolderName  = models.CharField(max_length = 255, verbose_name = 'Account Holder')
    Employer = models.CharField(max_length = 255, blank = True)
    TotalDue = models.BigIntegerField()
    Balance = models.BigIntegerField()
    DaysInArrears = models.IntegerField()
    MobilePhone = models.CharField(max_length = 15, blank = True)

debtors/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist

from.models import Paylater_Debtor

class Search(forms.Form):
    search = forms.CharField(widget = forms.TextInput(attrs = {'id' : 'searchField','class' : 'form-control'}))


    def find(self, param = 3):
        data = self.cleaned_data
        no_result_flag = False
        try:
            query_set = Paylater_Debtor.objects.filter(AccountHolderName__icontains = data['search']).order_by('AccountHolderName')
            count = Paylater_Debtor.objects.filter(AccountHolderName__icontains = data['search']).count()
            if count == 0:
                no_result_flag = True
                count = param
            elif count < param:
                count = param

            result = [query_set[x:x + (count//param)] for x in xrange(0, count, count//param)]

        except:
            result = ''

        return [result, no_result_flag]

    def populate(self, param = 3):
        try:
            query_set = Paylater_Debtor.objects.all()
            count = Paylater_Debtor.objects.all().count()
            if count < param:
                count = param
            result = [query_set[x:x + (count//param)] for x in xrange(0, count, count//param)]
        except:
            result = ''

        return result

debtors/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import Search
from django.core.urlresolvers import reverse




# Create your views here.

def index(request):

        search_form = Search(auto_id = False)
        result = search_form.populate(3)
        context = {'search_form' : search_form, 'result' : result, 'no_result_flag' : False}
        return render(request,  'debtors/index.html', context)

def search(request):
    if request.method == 'GET':
        if request.GET.get('search'):
            search_form = Search(request.GET)
            if search_form.is_valid():
                data = search_form.find(3 )
                result = data[0]
                no_result_flag = data[1]
                if no_result_flag:
                    result = 'No Record Found'
                context = {'search_form': search_form, 'result' : result, 'no_result_flag' : no_result_flag}
                return render(request, 'debtors/index.html', context)
        else:
            return HttpResponseRedirect(reverse('debtors:index'))

debtors/templates/debtors/index.html
{% load staticfiles %}
<! DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="SearchApp, SearchApp">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="assets/images/logo.png" type="image/x-icon">
  <meta name="description" content="">
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;subset=latin">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900">
  <link rel="stylesheet" href="{% static 'debtors/assets/et-line-font-plugin/style.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'debtors/assets/bootstrap-material-design-font/css/material.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'debtors/assets/tether/tether.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'debtors/assets/bootstrap/css/bootstrap.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'debtors/assets/socicon/css/socicon.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'debtors/assets/animate.css/animate.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'debtors/assets/theme/css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'debtors/assets/mobirise/css/mbr-additional.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'debtors/css/normalize.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'debtors/css/style.css' %}" type="text/css">

  
  
</head>
<body style=" background-color: rgb(0, 168, 133); padding-top: 20px; ">



<section class="mbr-section mbr-section-hero mbr-section-full" id="index-header1-0" style="background-color: rgb(0, 168, 133);  ">


    <div class="mbr-table-cell"   >

        <div class="container" style="margin-top:0px;   ">

            <div class="row">
               <div id="bottomFormDiv" class="mbr-section col-md-10 col-md-offset-1 text-xs-center"  >
                   <div  class="col-xs-12 col-lg-10 col-lg-offset-1">
                        <form id="bottomForm" class="mbr-form" action="{% url 'debtors:search' %}" method="get" >

                            <div class="mbr-subscribe mbr-subscribe-dark input-group">
                                {{ search_form.search }}
                                <span class="input-group-btn"><button type="submit" class="btn btn-primary">SEARCH FOR DEBTOR</button></span>
                            </div>
                        </form>
                   </div>
               </div>
            </div>


            <div class="row">
                {% if no_result_flag %}
                    <div class="col-xs-12 lead" style="font-family: 'Raleway', sans-serif;color: #ffffff; text-align: center;">
                        <p style="font-size: 70px;">{{ result }} </p>
                    </div>
                {%  else %}
                    {% for value in result %}
                        <div class="col-xs-12 col-md-4 lead" style="font-family: 'Raleway', sans-serif;color: #ffffff;">
                            {% for data in value %}
                                <p style="height: 20px">{{ data.AccountHolderName }}  N{{ data.TotalDue }},  {{ data.DaysInArrears }} days in arrears.</p>
                            {% endfor %}

                        </div>
                    {% endfor %}
                {% endif %}
            </div>



        </div>
    </div>

</section >


<footer class="mbr-small-footer mbr-section mbr-section-nopadding" id="index-footer1-0" style="background-color: rgb(50, 50, 50); padding-top: 1.75rem; padding-bottom: 1.75rem;">
    
    <div class="container">
        <p class="text-xs-center">Copyright (c) 2016 Apps</p>
    </div>
</footer>



  <script src="{% static 'debtors/assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'debtors/assets/tether/tether.min.js' %}"></script>
  <script src="{% static 'debtors/assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'debtors/assets/smooth-scroll/SmoothScroll.js' %}"></script>
  <script src="{% static 'debtors/assets/viewportChecker/jquery.viewportchecker.js' %}"></script>
  <script src="{% static 'debtors/assets/theme/js/script.js' %}"></script>
  <script src="{% static 'debtors/assets/formoid/formoid.min.js' %}"></script>



  
  <input name="animation" type="hidden">
  </body>
</html>